### ISSUE TITLE
Error parsing command <toggleexternalmap 512>

### ISSUE THREAD

**Issue by pasiosterman** [Snidor/ExternalMapMod#1]
Tried running the command from WurmConsole with various values in size.
toggleexternalmap 512

Tried with both classic livemap and your LiveHudMap.

```java
Error parsing command <toggleexternalmap 512>
org.gotti.wurmunlimited.modloader.classhooks.HookException: java.lang.reflect.InvocationTargetException
	at org.gotti.wurmunlimited.modloader.classhooks.HookManager.invoke(HookManager.java:354)
	at com.wurmonline.client.console.WurmConsole.handleInput2(WurmConsole.java)
	at com.wurmonline.client.console.WurmConsole.handleInput(WurmConsole.java:250)
	at com.wurmonline.client.renderer.gui.ConsoleComponent.handleInput(ConsoleComponent.java:42)
	at com.wurmonline.client.renderer.gui.WurmInputField.keyTyped(WurmInputField.java:739)
	at com.wurmonline.client.renderer.gui.HeadsUpDisplay.keyTyped(HeadsUpDisplay.java:1117)
	at com.wurmonline.client.WurmEventHandler.keyTyped(WurmEventHandler.java:160)
	at com.wurmonline.client.WurmEventHandler.handleKeyEvents(WurmEventHandler.java:438)
	at com.wurmonline.client.WurmEventHandler.handleEvents(WurmEventHandler.java:410)
	at com.wurmonline.client.WurmClientBase.handleEvents(WurmClientBase.java:375)
	at com.wurmonline.client.WurmClientBase.runGameLoop(WurmClientBase.java:531)
	at com.wurmonline.client.WurmClientBase.runConnectionLoop(WurmClientBase.java:325)
	at com.wurmonline.client.WurmClientBase.runGame(WurmClientBase.java:304)
	at com.wurmonline.client.WurmClientBase.run(WurmClientBase.java:1601)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gotti.wurmunlimited.modsupport.console.ModConsole$1$1.invoke(ModConsole.java:52)
	at org.gotti.wurmunlimited.modloader.classhooks.HookManager.invoke(HookManager.java:344)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: com/wurmonline/client/renderer/gui/ExternalMapWindow
	at externalmapmod.ExternalMapMod.handleInput(ExternalMapMod.java:35)
	at com.wurmonline.client.console.WurmConsole.handleDevInput(WurmConsole.java)
	at com.wurmonline.client.console.WurmConsole.handleInput2$1(WurmConsole.java:594)
	... 19 more
```

Mods installed

1.  archeogroup
2. archerymod
3. betterlight
4. compass
5. externalmapmod
6. freecammod
7. livemap
8. timerbeep

**Comment by Snidor** [comment]
it's possible you don't play on sklotopolis?
this is atm. just available for the sklotopolis server. that's one reason why i don't announced them without there.

same is for my version of the livehudmap, which i expanded with the deed data from sklotopolis.. and it's implemented to work with the sklo specific data.

**Comment by pasiosterman** [comment]
I do play on Sklotopolis under the name Vipsu. Your version of Livemap works fine, but this one doesn't even start for some reason.

**Comment by pasiosterman** [comment]
Latest update fixed the issue, works now.
Nice!
